const prompt = require('prompt-sync')({ sigint: true });
console.log('   GGGGGGG   OOOOOOOO   NN    NN   EEEEEEE')
console.log('   GG        OO    OO   NNN   NN   EE')
console.log('   GG        OO    OO   NN NN NN   EEEEEE')
console.log('   GG   GG   OO    OO   NN   NNN   EE'  )
console.log('   GGGGGGG   OOOOOOOO   NN    NN   EEEEEEE')
console.log("")
console.log("")
console.log('               ┊┊┊┊┊╭╭╭╮╮╮┊┊┊┊ ')
console.log('               ┊┊┊┊┊╰╰╲╱╯╯┊┊┊┊ ')
console.log('               ┊┏╮╭┓╭━━━━━━╮┊┊')
console.log('               ┊╰╮╭╯┃┈┈┈┈┈┈┃┊┊')
console.log('               ┊┊┃╰━╯┈┈╰╯┈┈┃┊┊')
console.log('               ┊┊┃┈┈┈┈┈┈┈╰━┫┊┊')
console.log('               ╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲')
console.log("")
console.log("")
console.log('FFFFF  IIII    SSSS   HH  HH   IIII   NN    NN   GGGGGGG')
console.log('FF      II    SS      HH  HH    II    NNN   NN   GG')
console.log('FFFFF   II    SSSS    HHHHHH    II    NN NN NN   GG')
console.log('FF      II        SS  HH  HH    II    NN   NNN   GG   GG')
console.log('FF     IIII   SSSSS   HH  HH   IIII   NN    NN   GGGGGGG')
console.log("")
console.log("")
console.log("============================================================================")
console.log("============================================================================")
console.log("")
console.log("")

let  clearSplash =prompt("Press [ENTER] to CONTINUE.")
console.log("")
console.log("")
console.log("============================================================================")
console.log("============================================================================")
console.log("")
console.log("")
console.log("")
console.log("")
console.log("You've gone fishing! Try to maximize the value of your caught fish.")
console.log("")
console.log("")
console.log("You can fish for six hours (till 12:00pm) and can catch at most 10 lbs of fish.")
console.log("")
console.log("")
console.log("============================================================================")
console.log("============================================================================")
console.log("")
console.log("")

